before_script:
  - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - chmod 400 "$SSH_PRIVATE_KEY"
  - ssh-add "$SSH_PRIVATE_KEY"
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

stages:
  - deploy

docker-image:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "$DOCKER_PASSWORD" -p "$DOCKER_PASSWORD" registry.digitalocean.com
    - docker build -t scraper-image .
    - docker tag scraper-image registry.digitalocean.com/buff163-scraper-registry/scraper-image
    - docker push registry.digitalocean.com/buff163-scraper-registry/scraper-image
    - ssh root@$DROPLET_IP "docker login -u "$DOCKER_PASSWORD" -p "$DOCKER_PASSWORD" registry.digitalocean.com && docker stop scraper-container && docker rm $(docker ps --filter status=exited -q) && docker pull DOCKER_IMAGE && docker run -d --name scraper-container --restart always -p 3000:3000 $DOCKER_IMAGE_NAME"