variables:
  IMAGE: europe-west6-docker.pkg.dev/$PROJECT_ID/buff163-scraper/buff163-scraper-img

stages:
  - build

docker-image:
  image: google/cloud-sdk:latest
  services:
    - docker:dind
  stage: build
  script:
    - gcloud auth activate-service-account --key-file $SA_AUTH
    - gcloud config set project $PROJECT_ID
    - gcloud auth configure-docker
    - gcloud builds submit --tag $IMAGE
    - gcloud app deploy --image-url=$IMAGE
