stages:
  - deploy

deploy-job:
  stage: deploy

  image: docker:latest
  services:
    - docker:dind

  before_script:
      - 'command -v ssh-agent >/dev/null || ( apk update && apk add openssh)'
      - eval $(ssh-agent -s)
      - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
      - mkdir -p ~/.ssh
      - chmod 644 ~/.ssh
      - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
      - touch ~/.ssh/known_hosts
      - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
      
  script:
    - docker login -u "$DOCKER_PASSWORD" -p "$DOCKER_PASSWORD" registry.digitalocean.com
    - docker build -t scraper-image .
    - docker tag scraper-image registry.digitalocean.com/buff163-scraper-registry/scraper-image
    - docker push registry.digitalocean.com/buff163-scraper-registry/scraper-image
    - ssh root@$DROPLET_IP "docker login -u '$DOCKER_PASSWORD' -p '$DOCKER_PASSWORD' registry.digitalocean.com && 
                            docker ps -aq | xargs docker rm -f &&
                            docker pull registry.digitalocean.com/buff163-scraper-registry/scraper-image && 
                            docker run -d --name scraper-container --restart always -p 3000:3000 registry.digitalocean.com/buff163-scraper-registry/scraper-image"