before_script:
  - apk add --no-cache --upgrade bash

stages:
  - deploy

docker-image:
  image: docker:latest
  services:
    - docker:dind
  stage: deploy
  script:
    - docker login -u "$DOCKER_PASSWORD" -p "$DOCKER_PASSWORD" registry.digitalocean.com
    - docker build -t scraper-image .
    - docker tag scraper-image registry.digitalocean.com/buff163-scraper-registry/scraper-image
    - docker push registry.digitalocean.com/buff163-scraper-registry/scraper-image
    - sshpass -p $DROPLET_PASSWORD ssh -o StrictHostKeyChecking=no root@$DROPLET_IP "docker login -u "$DOCKER_PASSWORD" -p "$DOCKER_PASSWORD" registry.digitalocean.com && docker stop scraper-container && docker rm $(docker ps --filter status=exited -q) && docker pull DOCKER_IMAGE && docker run -d --name scraper-container --restart always -p 3000:3000 $DOCKER_IMAGE_NAME"
  
#Env vars to add to gitlab:
# DROPLET_PASSWORD, DROPLET_IP