stages:
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

deploy:
  stage: deploy
  only:
    - main  # Trigger deployment only on changes to the master branch
  script:
    - docker login -u "$DOCKER_PASSWORD" -p "$DOCKER_PASSWORD" registry.digitalocean.com
    - docker build -t scraper-image .
    - docker push registry.digitalocean.com/buff163-scraper-registry/scraper-image