stages:
  - deploy

docker-image:
  image: docker:latest
  services:
    - docker:dind
  stage: deploy
  script:
    - docker login -u "$DOCKER_PASSWORD" -p "$DOCKER_PASSWORD" registry.digitalocean.com
    - docker build -t scraper-image .
    - docker tag scraper-image registry.digitalocean.com/buff163-scraper-registry/scraper-image
    - docker push registry.digitalocean.com/buff163-scraper-registry/scraper-image